version: '3'

services:
  consul:
    image: consul:1.15
    ports:
      - "8500:8500"  # HTTP API
      - "8600:8600/udp"  # DNS
    command: agent -dev -client=0.0.0.0
    networks:
      - app-network

  service1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=backend
      - SERVICE_PORT=8080
      - SERVER_ID=service1
    networks:
      - app-network
    depends_on:
      - consul

  service2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=backend
      - SERVER_ID=service2
      - SERVICE_PORT=8081
    networks:
      - app-network
    depends_on:
      - consul

  service3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=backend
      - SERVICE_PORT=8082
      - SERVER_ID=service3
    networks:
      - app-network
    depends_on:
      - consul

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - consul

networks:
  app-network:
    driver: bridge

volumes:
  nginx_config:
